# Generated by Django 6.0.5 on 2026-05-14 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="taskmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "pending"), ("status", "delayed"), _connector="OR"
                ),
                fields=("user", "name"),
                name="unique_tasks_per_user",
            ),
        ),
    ]
